---
# This playbook performs service cleanup for contiv network.
#
# Note: cleanup is not expected to fail, so we set ignore_errors to yes here

- hosts: all
  become: true
  tasks:
    - include_vars: roles/{{ item }}/defaults/main.yml
      with_items:
        - "contiv_network"
        - "contiv_storage"
        - "swarm"
        - "kubernetes"
        - "ucp"
        - "docker"
        - "etcd"
    - include: roles/{{ item }}/tasks/cleanup.yml
      with_items:
        - contiv_network
      static: no
      ignore_errors: yes
